include theos/makefiles/common.mk

BUNDLE_NAME = BLightAlertSettings
BLightAlertSettings_FILES = /mnt/d/codes/blightalert/blightalertsettings/BLightAlertSettingsController.mm
BLightAlertSettings_INSTALL_PATH = /Library/PreferenceBundles
BLightAlertSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
BLightAlertSettings_PRIVATE_FRAMEWORKS = Preferences
BLightAlertSettings_CFLAGS = -fobjc-arc
BLightAlertSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk

all::
